
server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jeab-fast-blog-api?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456     # 密码
    timeout: 60000ms  # 超时时间
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
